%YAML:1.0

############################ COMMON OPTIONS ###########################

# the number of loading pcd files
file_num: 5000

# downsampling options: voxel
ds_voxel_x: 0.5
ds_voxel_y: 0.5
ds_voxel_z: 0.5

# the number of samples in trainset
trainset_num: 10
